import React, { useState, useEffect } from 'react';
import {
  Box,
  Tab,
  Tabs,
  Typography,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Card,
  CardContent,
  Button
} from '@mui/material';
import { Line } from 'react-chartjs-2';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

// Define AnalysisResult interface
export interface AnalysisResult {
  id: number; // Auto-incremented ID
  postId: string;
  date: string;
  overallScore: number;
  overallSentiment: string;
  topPositiveWords?: string[]; // Optional fields
  topNegativeWords?: string[];
  scoreMagnitude?: number;
}

interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

function TabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;
  return (
    <div hidden={value !== index} {...other}>
      {value === index && <Box sx={{ p: 3 }}>{children}</Box>}
    </div>
  );
}

export const Admin = () => {
  const [value, setValue] = useState(0);
  const [analysisHistory, setAnalysisHistory] = useState<AnalysisResult[]>([]);
  const [topPosts, setTopPosts] = useState<AnalysisResult[]>([]);
  const [algorithmInfo] = useState({
    name: 'Sentiment Analysis Algorithm',
    accuracy: '85%',
    precision: '82%',
    recall: '88%',
    formula: 'sentiment = analyze(text)',
  });
  const [newPostId, setNewPostId] = useState('');
  const [newOverallScore, setNewOverallScore] = useState<number>(0);
  const [newOverallSentiment, setNewOverallSentiment] = useState('');
  const navigate = useNavigate();

    // Fetch analysis history function
  const fetchAnalysisHistory = async () => {
    try {
      const response = await axios.get<AnalysisResult[]>('/api/getResults');
      console.log('Fetched analysis history:', response.data);
      if (Array.isArray(response.data)) {
        setAnalysisHistory(response.data);
      } else {
        console.error('Expected an array, but got:', response.data);
        setAnalysisHistory([]);
      }
    } catch (error) {
      console.error('Error fetching analysis history:', error);
      setAnalysisHistory([]);
    }
  };

      // Fetch top posts function should be defined here
      const fetchTopPosts = async () => {
        try {
          const response = await axios.get<AnalysisResult[]>('/api/getTopPosts');
          console.log('Top posts fetched:', response.data); // Log the response
          setTopPosts(response.data);
        } catch (error) {
          console.error('Error fetching top posts:', error);
        }
        };

   // Call fetch functions in useEffect
   useEffect(() => {
    fetchAnalysisHistory();
    fetchTopPosts(); // Ensure this is called here
  }, []);


  const handleNewPostSubmission = async () => {
    const newResult: AnalysisResult = {
      id: 0, // This will be generated by the database
      postId: newPostId,
      date: new Date().toISOString(),
      overallScore: newOverallScore,
      overallSentiment: newOverallSentiment,
      topPositiveWords: [],
      topNegativeWords: [],
      scoreMagnitude: 0,
    };

    try {
      const response = await axios.post('/api/saveResult', newResult);
      // Assuming the backend returns the newly created post with the ID
      setAnalysisHistory((prevHistory) => [...prevHistory, response.data as AnalysisResult]);
      setNewPostId('');
      setNewOverallScore(0);
      setNewOverallSentiment('');
      fetchTopPosts(); // Refresh top posts after a new submission
    } catch (error) {
      console.error('Error submitting new post:', error);
    }
  };

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    handleNewPostSubmission();
    console.log(handleSubmit);
  };

  const handleDeletePost = async (id: number) => {
    try {
      await axios.delete(`/api/deletePost/${id}`);
      setAnalysisHistory((prev) => prev.filter((post) => post.id !== id));
      setTopPosts((prev) => prev.filter((post) => post.id !== id));
      console.log(`Post with ID ${id} deleted successfully`);
    } catch (error) {
      console.error('Error deleting post:', error);
    }
  };

  const handleDeleteAllPosts = async () => {
    try {
      await axios.delete('/api/deleteAllPosts');
      setAnalysisHistory([]);
      setTopPosts([]);
      console.log('All posts deleted successfully');
    } catch (error) {
      console.error('Error deleting all posts:', error);
    }
  };

  const getWeeklyScoreSums = () => {
    const weekScores: { [key: string]: number } = {};
    analysisHistory.forEach(result => {
      const date = new Date(result.date);
      const weekKey = `${date.getFullYear()}-W${getWeekNumber(date)}`;
      weekScores[weekKey] = (weekScores[weekKey] || 0) + result.overallScore;
    });
    return {
      labels: Object.keys(weekScores),
      data: Object.values(weekScores),
    };
  };

  const weeklyData = getWeeklyScoreSums();
  const chartData = {
    labels: weeklyData.labels,
    datasets: [{
      label: 'Total Overall Score per Week',
      data: weeklyData.data,
      borderColor: 'rgb(75, 192, 192)',
      backgroundColor: 'rgba(15, 10, 222, 1)',
      borderWidth: 1,
      tension: 0.1,
    }],
  };

  const options = {
    responsive: true,
    scales: {
      x: {
        title: {
          display: true,
          text: 'Week',
        },
      },
      y: {
        title: {
          display: true,
          text: 'Total Overall Score',
        },
        beginAtZero: true,
      },
    },
    plugins: {
      legend: {
        position: 'top' as const,
      },
      title: {
        display: true,
        text: 'Weekly Score Analytics',
      },
    },
  };

  const handleChange = (_: React.SyntheticEvent, newValue: number) => {
    setValue(newValue);
  };

  const handleLogout = () => {
    navigate('/'); // Redirect to homepage
  };

  return (
    <Box sx={{ width: '100%', padding: 3 }}>
      <Paper elevation={3} sx={{ padding: 2, marginBottom: 2 }}>
        <Typography variant="h4" gutterBottom>Admin Dashboard</Typography>
        <Tabs value={value} onChange={handleChange}>
          <Tab label="Algorithm Info" />
          <Tab label="Post History" />
          <Tab label="Top Posts" />
          <Tab label="Analytics" />
        </Tabs>
        <Button variant="contained" color="secondary" onClick={handleLogout} sx={{ marginTop: 2 }}>
          Logout
        </Button>
      </Paper>
      <TabPanel value={value} index={0}>
        <Card>
          <CardContent>
            <Typography variant="h6">Algorithm Information</Typography>
            <Typography>Name: {algorithmInfo.name}</Typography>
            <Typography>Accuracy: {algorithmInfo.accuracy}</Typography>
            <Typography>Precision: {algorithmInfo.precision}</Typography>
            <Typography>Recall: {algorithmInfo.recall}</Typography>
            <Typography variant="h6" sx={{ mt: 2 }}>Formula:</Typography>
            <Typography sx={{ fontFamily: 'monospace' }}>{algorithmInfo.formula}</Typography>
          </CardContent>
        </Card>
      </TabPanel>
      <TabPanel value={value} index={1}>
        <Button variant="contained" color="error" onClick={handleDeleteAllPosts} sx={{ marginTop: 2 }}>
          Delete All Posts
        </Button>
        <TableContainer component={Paper} sx={{ marginTop: 2 }}>
          <Table>
            <TableHead>
              <TableRow>
                <TableCell>Post ID</TableCell>
                <TableCell>Date</TableCell>
                <TableCell>Overall Score</TableCell>
                <TableCell>Overall Sentiment</TableCell>
                <TableCell>Actions</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {analysisHistory.map((result) => (
                <TableRow key={`${result.id}-${result.date}`}>  
                  <TableCell>{result.postId}</TableCell>
                  <TableCell>{new Date(result.date).toLocaleString()}</TableCell>
                  <TableCell>{result.overallScore}</TableCell>
                  <TableCell>{result.overallSentiment}</TableCell>
                  <TableCell>
                    <Button variant="contained" color="error" onClick={() => handleDeletePost(result.id)}>
                      Delete
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </TabPanel>
      <TabPanel value={value} index={2}>
        <TableContainer component={Paper}>
          <Table>
            <TableHead>
              <TableRow>
                <TableCell>Post ID</TableCell>
                <TableCell>Date</TableCell>
                <TableCell>Overall Score</TableCell>
                <TableCell>Overall Sentiment</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {topPosts.map((post) => (
                <TableRow key={post.id}> {/* Ensure `post.id` is unique */}
                  <TableCell>{post.postId}</TableCell>
                  <TableCell>{isNaN(new Date(post.date).getTime()) ? 'Invalid Date' : new Date(post.date).toLocaleString()}</TableCell>
                  <TableCell>{post.overallScore}</TableCell>
                  <TableCell>{post.overallSentiment}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </TabPanel>
      <TabPanel value={value} index={3}>
        <Line options={options} data={chartData} />
      </TabPanel>
    </Box>
  );
};

// Helper function to get week number from a date
const getWeekNumber = (date: Date) => {
  const startDate = new Date(date.getFullYear(), 0, 1);
  const days = Math.floor((date.valueOf() - startDate.valueOf()) / 86400000);
  return Math.ceil((days + startDate.getDay() + 1) / 7);
};

export default Admin;
